### ISSUE TITLE
Failing on install Zimbra 8.5.1.

### ISSUE THREAD

**Issue by lucasdiedrich** [ekros/zimcleaner#4]
This is the stacktrace, any sugestions?

[zimbra@mailserver ~]$ zmzimletctl install zmcleaner.zip 
java.io.FileNotFoundException: zimlet description not found: zmcleaner.xml
	at com.zimbra.cs.zimlet.ZimletFile.initZimletDescription(ZimletFile.java:252)
	at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:208)
	at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:165)
	at com.zimbra.cs.zimlet.ZimletFile.<init>(ZimletFile.java:146)
	at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1881)
	at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:1973)
[] ERROR: Error
java.io.FileNotFoundException: zimlet description not found: zmcleaner.xml
	at com.zimbra.cs.zimlet.ZimletFile.initZimletDescription(ZimletFile.java:252)
	at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:208)
	at com.zimbra.cs.zimlet.ZimletFile.initialize(ZimletFile.java:165)
	at com.zimbra.cs.zimlet.ZimletFile.<init>(ZimletFile.java:146)
	at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1881)
	at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:1973)

**Comment by lucasdiedrich** [comment]
Its because of the zip name, no problem at all, but it doesn't work either, i double-click the extension in the web UI and nothing happens. =/

**Comment by lucasdiedrich** [comment]
Forget about it again, it turns out the tab was loaded on top bar, not the left one. 

Everything is working.
